fixing precursors property
otherwise error:
```
site-packages/pymzml/spec.py in precursors(self)
    169             precursor(list): list of precursor ids for this spectrum.
    170         """
--> 171         if self._precursors is None:
    172             precursors = self.element.findall(
    173                 "./{ns}precursorList/{ns}precursor".format(ns=self.ns)

AttributeError: 'Spectrum' object has no attribute '_precursors'
```